#!/usr/bin/perl

# This is a perl script for generating lookup tables
# full of integer white noise.
#
# Invoke as ./fade_table.pl 32 15
# Where 10 is the number of lines in the table and 15
# is the largest number to make.

use strict;
use warnings;

my $numvals = shift;
my $maxval = shift;
$maxval += 1;

print "/* Generated by noise_table.pl $numvals $maxval */\n";
print "static const unsigned char noise[] = {\n  ";

my $i;
for ( $i = 0 ; $i < $numvals ; $i++ ) {
  #make random number
  printf ("%3d", rand($maxval));

  #newlines and commas
  if (0 == ($i + 1) % 20 and $i != $numvals - 1) {
    print ",\n  ";
  } elsif ($i != $numvals - 1) {
    print ",";
  }
}

print "};\n";
